media/gpu/v4l2: Explicitly declare MT21DecompressorJob deconstructor
Chromium style check gives the following error on Linux builds:

../../media/gpu/v4l2/mt21/mt21_decompressor.h:46:8: error: [chromium-style] Classes that are ref-counted should have explicit destructors that are declared protected or private.
   46 | struct MT21DecompressionJob : public base::RefCounted<MT21DecompressionJob> {
      |        ^
../../media/gpu/v4l2/mt21/mt21_decompressor.h:46:31: note: [chromium-style] 'MT21DecompressionJob' inherits from 'base::RefCounted<MT21DecompressionJob>' here
   46 | struct MT21DecompressionJob : public base::RefCounted<MT21DecompressionJob> {
      |                               ^

Since MT21DecompressorJob has no actual state or resources to take care
of, just explicitly declare a private default deconstructor.

Bug: b:258331312, b:291169645
Change-Id: I8e1f222791223b3e244eeee9f2cf713460cee902
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4710353
Reviewed-by: Miguel Casas-Sanchez <mcasas@chromium.org>
Commit-Queue: Chen-Yu Tsai <wenst@chromium.org>
Reviewed-by: Justin Green <greenjustin@google.com>
Cr-Commit-Position: refs/heads/main@{#1175279}
NOKEYCHECK=True
GitOrigin-RevId: 46d59e863991e989a23c0489b37252adb8d2dbd9