RELAND: media/gpu/v4l2: Remove BufferAffinityTracker
Original CL broke lacros-arm-archive-rel bot, probably because
I wrote GUARDED_BY() when I should have used GUARDED_BY_CONTEXT
instead. Concrete error was:

../../media/gpu/v4l2/v4l2_device.h:538:18: error: use of undeclared identifier 'sequence_checker_'
GUARDED_BY(sequence_checker_);

PS0 contains the reverted CL, subsequent patches the fixes.

Original CL description -----------------------------------------------

BufferAffinityTracker is supposed to be a wrapper around a map
(from id to a correlative index 0... max size).  There're
multiple strangenesses in that class: Method naming and comments
don't follow Chromium convention, uses an unnecessary lock, and
more importantly it carries out a simple map operation behind a
complicated class (which only has a use site).

This CL removes said class and moves the logic directly to its only user. Note how mutual exclusion condition is enforced at compile
time via GUARDED_BY(sequence_checker_).

Bug: b:279980150
Change-Id: Ie378eb1377f935b70643a70b76178758c844917d
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4519943
Reviewed-by: Nathan Hebert <nhebert@chromium.org>
Commit-Queue: Miguel Casas-Sanchez <mcasas@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1144788}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4537783
Cr-Commit-Position: refs/heads/main@{#1144887}
NOKEYCHECK=True
GitOrigin-RevId: 76e91ead5dd746e8d89677be9194268a627f8072