Tie `use_alsa` to !is_apple
... so that is_ios is also contemplated.

This fixes some compilation issues when building `wtf_unittests`
GN target in iOS builds with `use_blink` GN variable set, eg:

````
../../media/audio/alsa/alsa_input.h:8:10: fatal error:
'alsa/asoundlib.h' file not found
#include <alsa/asoundlib.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
````

BUG=1411704
R=liberato@chromium.org, dtapuska@chromium.org

Change-Id: I5263b1471cd007d26ade6ebb3df8835ffba1d985
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4223589
Reviewed-by: Frank Liberato <liberato@chromium.org>
Reviewed-by: Dave Tapuska <dtapuska@chromium.org>
Commit-Queue: Antonio Gomes <tonikitoo@igalia.com>
Cr-Commit-Position: refs/heads/main@{#1101669}
NOKEYCHECK=True
GitOrigin-RevId: cb3d3d1c5e989cc6792773dc6b1e46cefe68efb7