Fix a compilation error: incompatible operand types
Compiling natively on windows and introducing the
enable_platform_dts_audio = true parameter in args
will cause a compilation error.

Change-Id: I356f6ca192e138db8ec630b6143042520ab740fc
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4061635
Commit-Queue: Xiaohan Wang <xhwang@chromium.org>
Auto-Submit: 揚帆起航 <uioptt24@gmail.com>
Reviewed-by: Xiaohan Wang <xhwang@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1077887}
NOKEYCHECK=True
GitOrigin-RevId: 31f2cf7958555130c7b59dadd6d67ec5a2098af9