RELAND: media/gpu/v4l2: Simplify some V4L2Queue code
Original CL was reverted due to the ARM compiler not liking an
implicit cast.
```
[1700/1950] CXX obj/media/gpu/v4l2/v4l2/v4l2_queue.o
FAILED: obj/media/gpu/v4l2/v4l2/v4l2_queue.o
../../build/cros_cache/chrome-sdk/symlinks/arm64-generic+15502.0.0+target_toolchain/bin/aarch64-cros...(too long)
../../media/gpu/v4l2/v4l2_queue.cc:1150:16: error: non-constant-expression cannot be narrowed from type 'size_t' (aka 'unsigned long') to '__u32' (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
.count = count, .type = type_, .memory = memory, .flags = coherency};
^~~~~
../../media/gpu/v4l2/v4l2_queue.cc:1150:16: note: insert an explicit cast to silence this issue
.count = count, .type = type_, .memory = memory, .flags = coherency};
^~~~~
static_cast<__u32>( )
1 error generated.
```

PS0 contains the original CL and later patches the fix.

Cq-Include-Trybots: luci.chromium.try:lacros-arm64-generic-rel

Original CL description -----------------------------------------------

While working on [1] I found out some code there could be simpler.
This CL extracts that to ease code review. In particular:
- struct v4l2_requestbuffers is a POD and doesn't need memset(0),
can use designated initializers.
- There's no need to DCHECK(!free_buffers_); in the destructor
since the code anyway DeallocateBuffers() immediately after.
- DVQLOGF already prints the queue type, so there's no need to
dump it (as integer, confusingly).

No new functionality intended.

[1] https://chromium-review.googlesource.com/c/chromium/src/+/4619074

Bug: b:279980150
Change-Id: Ia58fc917f12fbe1b7bf8db1fc802efbcd6380058
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4621601
Reviewed-by: Nathan Hebert <nhebert@chromium.org>
Commit-Queue: Miguel Casas-Sanchez <mcasas@chromium.org>
Cr-Original-Commit-Position: refs/heads/main@{#1160102}
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/4629851
Cr-Commit-Position: refs/heads/main@{#1160264}
NOKEYCHECK=True
GitOrigin-RevId: 6f8fd4eeff3f299e712cc30cc322ae98610e85b9