[LinearBlock] Fix JNI signature generation for LinearBlock
The JNI generator fails to resolve the correct JNI signature when a type
annotation is placed in the middle of a qualified class name (e.g.,
MediaCodec.@Nullable LinearBlock), defaulting to the current package
instead (org/chromium/media/MediaCodec$LinearBlock). This causes a
runtime crash due to `NoSuchMethodError` - `W System.err:
java.lang.NoSuchMethodError: no non-static method "Lorg/chromium/media/
MediaCodecBridge$ObtainBlockResult;.block()Lorg/chromium/media/
MediaCodec$LinearBlock;"

This commit fixes the issue by directly importing MediaCodec.LinearBlock
and using the unqualified type name with the annotation in front
(@Nullable LinearBlock), allowing the JNI generator to resolve the
correct android.media.MediaCodec$LinearBlock signature.

Bug: 327625558
Change-Id: Ic9479063e8dd22f0b3797764d80ff3d73a868cc6
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/7750430
Reviewed-by: Eugene Zemtsov <eugene@chromium.org>
Commit-Queue: Phil Yan <philyan@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1613993}
NOKEYCHECK=True
GitOrigin-RevId: 2bcb275f722736b23ee1790530899d3a318337a1